# Generated by Django 4.1.7 on 2023-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthquests',
            name='emergency_contact',
            field=models.CharField(max_length=100, null=True, verbose_name='contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='healthquests',
            name='emergency_number',
            field=models.IntegerField(null=True, verbose_name='Número de emergencia'),
        ),
    ]
