# Generated by Django 4.1.7 on 2023-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0002_alter_healthquests_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthquests',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='healthquests',
            name='emergency_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de emergencia'),
        ),
    ]
