# Generated by Django 4.1.3 on 2022-11-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0002_alter_healthquests_ailments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthquests',
            name='identification',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de cedula'),
        ),
    ]
