# Generated by Django 4.1.3 on 2022-12-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0004_healthquests_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthquests',
            name='ailments',
            field=models.ManyToManyField(blank=True, to='HealthQuest.ailments', verbose_name='Padecimientos'),
        ),
        migrations.AlterField(
            model_name='healthquests',
            name='joint_problems',
            field=models.ManyToManyField(blank=True, to='HealthQuest.joint_problems', verbose_name='Problemas articulares'),
        ),
    ]
