# Generated by Django 4.1.4 on 2022-12-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0005_alter_healthquests_ailments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthquests',
            name='identification',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de cedula'),
        ),
    ]
