# Generated by Django 4.1.4 on 2022-12-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0006_alter_healthquests_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthquests',
            name='photo',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='photos/', verbose_name='Foto'),
        ),
    ]
