# Generated by Django 4.1.4 on 2022-12-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0008_alter_healthquests_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthquests',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Foto'),
        ),
    ]
