# Generated by Django 4.1.4 on 2023-01-09 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0011_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Monto de pago'),
        ),
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de facturación'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de pago'),
        ),
    ]
