# Generated by Django 4.1.4 on 2023-01-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0012_payments_amount_payments_date_payments_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthQuest.healthquests', verbose_name='Cliente'),
        ),
    ]
