# Generated by Django 4.1.7 on 2023-03-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuest', '0013_alter_payments_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthquests',
            name='photo',
        ),
    ]
